name: Test and Deploy
on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code from repo
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: deps-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test Code
        run: npm run test
      - name: Greet
        run: echo "Hi, peeps!"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code from repo
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: deps-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
          name: Vite App
