name: Test and Deploy
on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code from repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test Code
        run: npm run test
